// Licence register
export const API_LICENCE_REQUEST = "API_LICENCE_REQUEST";
export const API_LICENCE_SUCCESS = "API_LICENCE_SUCCESS";
export const API_LICENCE_FAILURE = "API_LICENCE_FAILURE";
export const API_REGISTER_SUCCESS = "API_REGISTER_SUCCESS";

export const GET_PROF_REQUEST = "GET_PROF_REQUEST";
export const GET_PROF_SUCCESS = "GET_PROF_SUCCESS";
export const GET_PROF_FAILURE = "GET_PROF_FAILURE";
export const WELCOME_CONNECTION = "WELCOME_CONNECTION";

export const GET_FILES = "GET_FILES";

export const GET_GAMES_INSTALLED = "GET_GAMES_INSTALLED";
export const GET_GAMES_NOT_INSTALLED = "GET_GAMES_NOT_INSTALLED";

export const API_TOKEN_DELETE = "API_TOKEN_DELETE";
export const API_TOKEN_DELETE_SUCCESS = "API_TOKEN_DELETE_SUCCESS";
export const API_TOKEN_DELETE_FAILURE = "API_TOKEN_DELETE_FAILURE";
export const API_TOKEN_DELETED = "API_TOKEN_DELETED";

export const API_TOKEN_REQUEST = "API_TOKEN_REQUEST";
export const API_TOKEN_SUCCESS = "API_TOKEN_SUCCESS";
export const API_TOKEN_FAILURE = "API_TOKEN_FAILURE";

export const API_TOKEN_VALIDATE = "API_TOKEN_VALIDATE";
export const API_TOKEN_VALIDATE_SUCCESS = "API_TOKEN_VALIDATE_SUCCESS";
export const API_TOKEN_VALIDATE_FAILURE = "API_TOKEN_VALIDATE_FAILURE";

export const API_TOKEN_SESSION = "API_TOKEN_SESSION";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_CLEAN = "USER_LOGOUT";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

export const LOADER_START = "LOADER_START";
export const LOADER_END = "LOADER_END";

export const DOWNLOAD_GAME = "DOWNLOAD_GAME";
export const DOWNLOAD_GAME_FAILURE = "DOWNLOAD_GAME_FAILURE";
export const DOWNLOAD_GAME_SUCCESS = "DOWNLOAD_GAME_SUCCESS";
export const INSTALLATION_GAME = "INSTALLATION_GAME";
export const INSTALLATION_GAME_FAILURE = "INSTALLATION_GAME_FAILURE";
export const INSTALLATION_GAME_SUCCESS = "INSTALLATION_GAME_SUCCESS";

export const PROCESS_START = "PROCESS_START";
export const PROCESS_START_FAILURE = "PROCESS_START_FAILURE";
export const PROCESS_START_SUCCESS = "PROCESS_START_SUCCESS";
export const PROCESS_END = "PROCESS_END";
export const PROCESS_END_FAILURE = "PROCESS_END_FAILURE";
export const PROCESS_END_SUCCESS = "PROCESS_END_SUCCESS";
